apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dask-worker
  name: dask-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dask-worker
    spec:
      containers:
      - command:
        - dask-worker
        - dask-scheduler:8786
        env:
        - name: IN_DOCKER
          value: 'True'
        - name: PYTHONPATH
          value: /src:/src/qed
        image: quanted/qed-dask
        name: dask-worker
        volumeMounts:
        - mountPath: /src
          name: dask-worker-src
      hostname: dask-worker
      restartPolicy: Always
      volumes:
      - hostPath:
          path: C:\git\qed_kube\qed_django
        name: dask-worker-src
