apiVersion: apps/v1
kind: Deployment
metadata:
  name: qed-nginx
  labels:
    app: qed-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qed-nginx
  template:
    metadata:
      labels:
        app: qed-nginx
    spec:
      containers:
      - name: qed-nginx
        image: quanted/qed_nginx:dev_kube
        imagePullPolicy: "Always"
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
          - mountPath: /etc/nginx/qed
            name: qed-nginx-certs
          - mountPath: /src/static
            name: qed-static
      restartPolicy: Always
      volumes:
        - name: qed-nginx-certs
          hostPath:
            path: /Users/dsmith/Documents/git/qed_kube/data/nginx-certs
            type: Directory
        - name: qed-static
          hostPath:
            path: /Users/dsmith/Documents/git/qed_kube/static_qed
            type: Directory